# Generated by Django 4.2.7 on 2026-01-12 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_chauffeur', models.CharField(choices=[('taxi', 'Taxi'), ('prive', 'Chauffeur Privé'), ('societe', 'Chauffeur Société')], default='prive', max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_voiture', models.CharField(blank=True, max_length=50, null=True)),
                ('societe', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_course_par_defaut', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_password', models.CharField(blank=True, help_text="Mot de passe pour l'application mobile (sera automatiquement hashé en SHA256)", max_length=255, null=True, verbose_name='Mot de passe mobile')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_conge', 'En congé')], default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HeureTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transport', models.CharField(choices=[('ramassage', 'Ramassage'), ('depart', 'Départ')], max_length=20)),
                ('heure', models.IntegerField(help_text='Heure au format 24h (ex: 6 pour 6h, 22 pour 22h)')),
                ('libelle', models.CharField(help_text="Libellé affiché (ex: 'Ramassage 6h')", max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Heure de transport',
                'verbose_name_plural': 'Heures de transport',
                'ordering': ['type_transport', 'ordre', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la société')),
                ('matricule_fiscale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matricule fiscale')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse de la société')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de la société')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la société')),
                ('contact_personne', models.CharField(blank=True, max_length=200, null=True, verbose_name='Personne à contacter')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transport', models.CharField(choices=[('ramassage', 'Ramassage'), ('depart', 'Depart')], max_length=20)),
                ('heure', models.IntegerField()),
                ('jour', models.CharField(max_length=20)),
                ('date_reelle', models.DateField()),
                ('prix_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('demande_validation', 'Demande validation'), ('payee', 'Payée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes_validation', models.TextField(blank=True, null=True)),
                ('demande_validation_at', models.DateTimeField(blank=True, null=True)),
                ('validee_at', models.DateTimeField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'unique_together': {('chauffeur', 'heure', 'type_transport', 'jour', 'date_reelle')},
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('societe_texte', models.CharField(blank=True, max_length=100, null=True)),
                ('voiture_personnelle', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('adresse_geocodee', models.TextField(blank=True, null=True, verbose_name='Adresse géocodée')),
                ('derniere_geolocalisation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.IntegerField()),
                ('type_transport', models.CharField(choices=[('ramassage', 'Ramassage'), ('depart', 'Depart')], max_length=20)),
                ('jour', models.CharField(max_length=20)),
                ('date_reelle', models.DateField()),
                ('prix_course', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_societe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agent')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur', verbose_name='Chauffeur')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.course')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'unique_together': {('agent', 'date_reelle'), ('chauffeur', 'heure', 'agent', 'type_transport', 'jour', 'date_reelle')},
            },
        ),
    ]
