# Generated by Django 4.2.7 on 2026-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
    ]
