# Generated by Django 4.2.7 on 2026-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_chauffeur_adresse_chauffeur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='point_depart_adresse',
            field=models.TextField(blank=True, default='rue rabat complexe zaoui sousse 4000', null=True, verbose_name='Adresse de départ'),
        ),
        migrations.AddField(
            model_name='course',
            name='point_depart_latitude',
            field=models.FloatField(blank=True, default=35.832, null=True, verbose_name='Latitude départ'),
        ),
        migrations.AddField(
            model_name='course',
            name='point_depart_longitude',
            field=models.FloatField(blank=True, default=10.61, null=True, verbose_name='Longitude départ'),
        ),
    ]
