# Generated by Django 4.2.7 on 2026-01-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_course_point_depart_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(verbose_name='Date de la réservation (toujours J+1)')),
                ('type_transport', models.CharField(choices=[('ramassage', 'Ramassage'), ('depart', 'Départ')], max_length=20, verbose_name='Type de transport')),
                ('statut', models.CharField(choices=[('reservee', 'Réservée'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='reservee', max_length=20, verbose_name='Statut de la réservation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes du chauffeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agent', verbose_name='Agent réservé')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur', verbose_name='Chauffeur qui réserve')),
                ('heure_transport', models.ForeignKey(help_text="Heure configurée dynamiquement dans l'admin", on_delete=django.db.models.deletion.CASCADE, to='gestion.heuretransport', verbose_name='Heure de transport')),
            ],
            options={
                'verbose_name': 'Réservation J+1',
                'verbose_name_plural': 'Réservations J+1',
                'ordering': ['date_reservation', 'heure_transport__heure', 'chauffeur'],
                'unique_together': {('agent', 'date_reservation', 'heure_transport', 'type_transport')},
            },
        ),
    ]
