# Generated by Django 4.2.7 on 2026-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('agent', 'date_reservation', 'heure_transport', 'type_transport', 'statut')},
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['reservee', 'confirmee'])), fields=('agent', 'date_reservation', 'heure_transport', 'type_transport'), name='unique_active_reservation'),
        ),
    ]
