# Generated by Django 4.2.7 on 2026-01-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('agent', 'date_reservation', 'heure_transport', 'type_transport')},
        ),
    ]
