# Generated by Django 4.2.7 on 2026-01-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_reservation',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['reservee', 'confirmee'])), fields=('agent', 'date_reservation', 'heure_transport', 'type_transport'), name='unique_active_reservation_per_agent'),
        ),
    ]
