# Generated by Django 4.2.7 on 2026-01-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_reservation_unique_active_reservation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_reservation', 'heure_transport__heure', 'chauffeur'], 'verbose_name': 'Réservation J+1', 'verbose_name_plural': 'Réservations J+1'},
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_reservation_per_agent',
        ),
    ]
