# Generated by Django 4.2.7 on 2026-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='point_depart_longitude',
            field=models.FloatField(blank=True, default=10.628, null=True, verbose_name='Longitude départ'),
        ),
    ]
