# Generated by Django 4.2.7 on 2026-01-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_course_point_depart_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='point_depart_latitude',
            field=models.FloatField(blank=True, default=35.8342, null=True, verbose_name='Latitude départ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='point_depart_longitude',
            field=models.FloatField(blank=True, default=10.6296, null=True, verbose_name='Longitude départ'),
        ),
    ]
