# Generated by Django 4.2.7 on 2026-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_course_point_depart_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='corrige_manuellement',
            field=models.BooleanField(default=False, verbose_name='Coordonnées corrigées manuellement'),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_correction_coords',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de correction des coordonnées'),
        ),
        migrations.AddField(
            model_name='agent',
            name='notes_correction',
            field=models.TextField(blank=True, null=True, verbose_name='Notes sur la correction'),
        ),
    ]
