# Generated by Django 4.2.7 on 2026-01-22 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0011_agent_corrige_manuellement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
    ]
