# Generated by Django 4.2.7 on 2026-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_course_validee_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
