# Generated by Django 4.2.7 on 2026-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_course_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='super_chauffeur',
            field=models.BooleanField(default=False, help_text='Si coché, ce chauffeur peut voir tous les chauffeurs et leurs courses', verbose_name='Super chauffeur (peut voir tous les chauffeurs)'),
        ),
    ]
