# Generated by Django 4.2.7 on 2026-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_chauffeur_super_chauffeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='super_chauffeur',
            field=models.BooleanField(default=False, verbose_name='Super chauffeur'),
        ),
    ]
