# Generated by Django 4.2.7 on 2026-01-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0003_course_point_depart_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('validation', 'Demande de validation'), ('info', 'Information'), ('alerte', 'Alerte')], max_length=20)),
                ('message', models.TextField()),
                ('vue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur')),
            ],
            options={
                'verbose_name': 'Notification mobile',
                'verbose_name_plural': 'Notifications mobiles',
            },
        ),
        migrations.CreateModel(
            name='ReservationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(verbose_name='Date de la course')),
                ('type_transport', models.CharField(choices=[('ramassage', 'Ramassage'), ('depart', 'Départ')], default='ramassage', max_length=20)),
                ('heure', models.IntegerField(verbose_name='Heure de la course')),
                ('statut', models.CharField(choices=[('reserve', 'Réservé'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='reserve', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agent')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur')),
            ],
            options={
                'verbose_name': "Réservation d'agent",
                'verbose_name_plural': "Réservations d'agents",
                'ordering': ['date_reservation', 'heure'],
                'unique_together': {('agent', 'date_reservation', 'heure', 'type_transport')},
            },
        ),
        migrations.CreateModel(
            name='MobileCourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_mobile', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('validee', 'Validée'), ('probleme', 'Problème')], default='a_faire', max_length=20)),
                ('heure_reelle', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.course')),
            ],
            options={
                'verbose_name': 'Statut mobile',
                'verbose_name_plural': 'Statuts mobiles',
                'unique_together': {('course', 'chauffeur')},
            },
        ),
    ]
