# Generated by Django 4.2.7 on 2026-01-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs_mobile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationAgent',
        ),
    ]
